import type { Metadata } from "next";
import "./globals.css";
import { sourceSans } from "./fonts";


export const metadata: Metadata = {
  title: "Simulandum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sourceSans.className}`}>
        {children}
      </body>
    </html>
  );
}
