import type { Metadata } from "next";
import "./globals.css";
import { sourceSans } from "./fonts";
import { ClerkProvider } from "@clerk/nextjs";
import { esMX } from "@clerk/localizations";


export const metadata: Metadata = {
  title: "Simulandum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider localization={esMX}>
    <html lang="es">
      <body className={`${sourceSans.className}`}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
